version: '3'
services:
    minecraft-pi:
        image: 'thebrokenrail/minecraft-pi-reborn:client'
        network_mode: 'host'
        user: '${USER_UID}'
        volumes:
            - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '${USER_HOME}/.minecraft-pi:/home/.minecraft'
        devices:
            - '/dev/dri:/dev/dri'
        environment:
            - 'HOME=/home'
            - 'DISPLAY=unix${DISPLAY}'
            - 'MCPI_FEATURES=${MCPI_FEATURES}'
            - 'MCPI_RENDER_DISTANCE=${MCPI_RENDER_DISTANCE}'
            - 'MCPI_USERNAME=${MCPI_USERNAME}'
            - 'MCPI_MODE=native'
