version: '3'
services:
    minecraft-pi:
        image: 'thebrokenrail/minecraft-pi-reborn:client'
        network_mode: 'host'
        volumes:
            - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '/tmp/.virgl_test:/tmp/.virgl_test'
            - '~/.minecraft-pi:/root/.minecraft'
        environment:
            - 'DISPLAY=unix${DISPLAY}'
            - 'MCPI_FEATURES=${MCPI_FEATURES}'
            - 'MCPI_USERNAME=${MCPI_USERNAME}'
            - 'MCPI_MODE=virgl'
